runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:gHLpi2n7NIFv+AhWhZSTeTVmMVCTXVX0IT1jWSsYJ4o=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
